name: 'snapchat_ads_source_integration_tests'

version: '0.8.0'
profile: 'integration_tests'
config-version: 2

vars:
    snapchat_ads_schema: snapchat_ads_source_integration_tests_1
    snapchat_ads_ad_account_history_identifier:  "snapchat_ad_account_history_data"
    snapchat_ads_ad_history_identifier: "snapchat_ad_history_data"
    snapchat_ads_ad_hourly_report_identifier: "snapchat_ad_hourly_report_data"
    snapchat_ads_ad_squad_history_identifier: "snapchat_ad_squad_history_data"
    snapchat_ads_ad_squad_hourly_report_identifier: "snapchat_ad_squad_hourly_report_data"
    snapchat_ads_campaign_history_identifier: "snapchat_campaign_history_data"
    snapchat_ads_campaign_hourly_report_identifier: "snapchat_campaign_hourly_report_data"
    snapchat_ads_creative_history_identifier: "snapchat_creative_history_data"
    snapchat_ads_creative_url_tag_history_identifier: "snapchat_creative_url_tag_history_data"
    snapchat_ads_campaign_geo_region_daily_report_identifier: "snapchat_campaign_geo_region_daily_report_data"
    snapchat_ads_campaign_geo_country_daily_report_identifier: "snapchat_campaign_geo_country_daily_report_data"

    snapchat_ads__conversion_fields: ['conversion_purchases']
    snapchat_ads__ad_hourly_passthrough_metrics:
      - name: conversion_add_billing
      - name: conversion_purchases
        alias: conversion_purchases_alias
      - name: conversion_page_views
      
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  snapchat_ads_source_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    snapchat_ad_hourly_report_data:
      +column_types:
        date: timestamp
    snapchat_creative_url_tag_history_data:
      +column_types:
        updated_at: timestamp